//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Tool.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_MAINFRAME                   128
#define IDR_ToolTYPE                    130
#define IDD_FORM                        310
#define IDD_PROTOTYPETOOL               311
#define IDD_NAVMESHTOOL                 312
#define IDD_TERRAINTOOL                 313
#define IDD_UITOOL                      314
#define IDD_RECTYZTOOL                  315
#define IDD_LOTOBJECTTOOL               316
#define IDC_WALL_PICTURE                1000
#define IDC_WALL_CATEGORY_SIDE          1001
#define IDC_WALL_RADIO_LEFT             1002
#define IDC_WALL_RADIO_RIGHT            1003
#define IDC_WALL_CATEGORY_UV            1004
#define IDC_WALL_TEXT_U                 1005
#define IDC_WALL_TEXT_V                 1006
#define IDC_WALL_EDIT_U                 1007
#define IDC_WALL_EDIT_V                 1008
#define IDC_WALL_TEXT_UVDEFINE          1009
#define IDC_WALL_CATEGORY_YZ_INT        1010
#define IDC_WALL_EDIT_Z_INT             1011
#define IDC_WALL_EDIT_V_INT             1012
#define IDC_WALL_TEXT_Z_INT             1013
#define IDC_WALL_TEXT_Y_INT             1014
#define IDC_WALL_TEXT_INTDEFINE         1015
#define IDC_WALL_CATEGORY_YZ_VERT       1016
#define IDC_WALL_TEXT_Z_VERT            1017
#define IDC_WALL_TEXT_Y_VERT            1018
#define IDC_WALL_EDIT_Z_VERT            1019
#define IDC_WALL_EDIT_Y_VERT            1020
#define IDC_WALL_TEXT_VERTDEFINE        1021
#define IDC_WALL_TEXT_TEXTURE           1022
#define IDC_WALL_LIST_TEXTURE           1023
#define IDC_WALL_TEXT_SIDEDEFINE        1024
#define IDC_WALL_CATEGORY_TRANSFORM     1025
#define IDC_WALL_CATEGORY_POSITION      1026
#define IDC_WALL_CATEGORY_ROTATION      1027
#define IDC_WALL_CATEGORY_SCALE         1028
#define IDC_WALL_TEXT_POS_X             1029
#define IDC_WALL_TEXT_POS_Y             1030
#define IDC_WALL_TEXT_POS_Z             1031
#define IDC_WALL_TEXT_ROT_X             1032
#define IDC_WALL_TEXT_ROT_Y             1033
#define IDC_WALL_TEXT_ROT_Z             1034
#define IDC_WALL_TEXT_SCALE_X           1035
#define IDC_WALL_TEXT_SCALE_Y           1036
#define IDC_WALL_TEXT_SCALE_Z           1037
#define IDC_WALL_EDIT_POS_X             1038
#define IDC_WALL_EDIT_POS_Y             1039
#define IDC_WALL_EDIT_POS_Z             1040
#define IDC_WALL_EDIT_ROT_X             1041
#define IDC_WALL_EDIT_ROT_Y             1042
#define IDC_WALL_EDIT_ROT_Z             1043
#define IDC_WALL_TEXT_ROT_WARNING       1044
#define IDC_WALL_RADIO_CUBE_ONE         1045
#define IDC_WALL_TEXT_X_VERT            1045
#define IDC_WALL_CATEGORY_CUBE          1046
#define IDC_WALL_EDIT_X_VERT            1046
#define IDC_WALL_RADIO_CUBE_MUL         1047
#define IDC_WALL_TEXT_X_INT             1047
#define IDC_WALL_EDIT_String_Name       1048
#define IDC_WALL_TEXT_NAME              1049
#define IDC_WALL_BUTTON_SAVE            1050
#define IDC_WALL_BUTTON_LOAD            1051
#define IDC_WALL_BUTTON_WIREFRAME       1052
#define IDC_WALL_TEXT_TEXTURE_DEFINE    1053
#define IDC_WALL_EDIT_X_INT             1054
#define IDC_WALL_CATEGORY_LOOK          1055
#define IDC_WALL_RADIO_BUFFER_TYPE_YZ   1056
#define IDC_WALL_RADIO_BUFFER_TYPE_XY   1057
#define IDC_WALL_RADIO_FRONT            1058
#define IDC_WALL_RADIO_BACK             1059
#define IDC_WALL_CATEGORY_COLLIDER_POS  1067
#define IDC_WALL_EDIT_COLLIDER_POS_X    1068
#define IDC_WALL_EDIT_COLLIDER_POS_Y    1069
#define IDC_WALL_EDIT_COLLIDER_POS_Z    1070
#define IDC_WALL_TEXT_COLLIDER_POS_X    1071
#define IDC_WALL_TEXT_COLLIDER_POS_Y    1072
#define IDC_WALL_TEXT_COLLIDER_POS_Z    1073
#define IDC_WALL_CATEGORY_COLLIDER_SIZE 1074
#define IDC_WALL_TEXT_COLLIDER_SIZE_X   1075
#define IDC_WALL_TEXT_COLLIDER_SIZE_Y   1076
#define IDC_WALL_TEXT_COLLIDER_SIZE_Z   1077
#define IDC_WALL_EDIT_COLLIDER_SIZE_X   1078
#define IDC_WALL_EDIT_COLLIDER_SIZE_Y   1079
#define IDC_WALL_EDIT_COLLIDER_SIZE_Z   1080
#define IDC_WALL_SLIDER_ALPHA           1081
#define IDC_WALL_EDIT_STRING_TEXTURE    1082
#define IDC_WALL_SLIDER_RED             1083
#define IDC_WALL_SLIDER_GREEN           1084
#define IDC_WALL_SLIDER_BLUE            1085
#define IDC_WALL_TEXT_COLLIDER_ALPHA    1086
#define IDC_WALL_TEXT_COLLIDER_RED      1087
#define IDC_WALL_TEXT_COLLIDER_GREEN    1088
#define IDC_WALL_TEXT_COLLIDER_BLUE     1089
#define IDC_WALL_EDIT_COLLIDER_ALPHA    1090
#define IDC_WALL_EDIT_COLLIDER_RED      1091
#define IDC_WALL_EDIT_COLLIDER_GREEN    1092
#define IDC_WALL_EDIT_COLLIDER_BLUE     1093
#define IDC_PROTOTYPE_TEXT_ARGB         1094
#define IDC_PROTOTYPE_EDIT_COLLIDER_ALPHA 1095
#define IDC_PROTOTYPE_EDIT_COLLIDER_RED 1096
#define IDC_PROTOTYPE_EDIT_COLLIDER_GREEN 1097
#define IDC_PROTOTYPE_EDIT_COLLIDER_POS_X 1098
#define IDC_PROTOTYPE_EDIT_COLLIDER_POS_Y 1099
#define IDC_PROTOTYPE_EDIT_COLLIDER_POS_Z 1100
#define IDC_PROTOTYPE_CATEGORY_COLLIDER_POS 1101
#define IDC_PROTOTYPE_TEXT_COLLIDER_POS_X 1102
#define IDC_PROTOTYPE_TEXT_COLLIDER_POS_Y 1103
#define IDC_PROTOTYPE_TEXT_COLLIDER_POS_Z 1104
#define IDC_PROTOTYPE_TEXT_COLLIDER_SIZE_X 1105
#define IDC_PROTOTYPE_TEXT_COLLIDER_SIZE_Y 1106
#define IDC_PROTOTYPE_TEXT_COLLIDER_SIZE_Z 1107
#define IDC_PROTOTYPE_EDIT_COLLIDER_SIZE_X 1108
#define IDC_PROTOTYPE_EDIT_COLLIDER_SIZE_Y 1109
#define IDC_PROTOTYPE_EDIT_COLLIDER_SIZE_Z 1110
#define IDC_PROTOTYPE_SLIDER_ALPHA      1111
#define IDC_PROTOTYPE_SLIDER_RED        1112
#define IDC_PROTOTYPE_SLIDER_GREEN      1113
#define IDC_PROTOTYPE_SLIDER_BLUE       1114
#define IDC_PROTOTYPE_EDIT_COLLIDER_BLUE 1115
#define ID_PICTURE1                     2000
#define IDC_LIST1                       2001
#define IDC_LIST5                       2002
#define IDC_EDIT23                      2003
#define IDC_EDIT24                      2004
#define IDC_EDIT25                      2005
#define IDC_EDIT26                      2006
#define IDC_EDIT1                       2007
#define IDC_EDIT13                      2008
#define IDC_EDIT14                      2009
#define IDC_EDIT15                      2010
#define IDC_EDIT16                      2011
#define IDC_EDIT17                      2012
#define IDC_EDIT18                      2013
#define IDC_EDIT19                      2014
#define IDC_EDIT20                      2015
#define IDC_EDIT21                      2016
#define IDC_EDIT22                      2017
#define IDC_EDIT27                      2018
#define IDC_BUTTON1                     2019
#define IDC_WALL_EDIT_SCALE_X           2019
#define IDC_BUTTON2                     2020
#define IDC_WALL_EDIT_SCALE_Y           2020
#define IDC_LIST2                       2021
#define IDC_EDIT30                      2021
#define IDC_WALL_EDIT_SCALE_Z           2021
#define IDC_LIST3                       2022
#define IDC_LIST4                       2023
#define IDC_EDIT2                       2024
#define IDC_EDIT3                       2025
#define IDC_EDIT4                       2026
#define IDC_EDIT5                       2027
#define IDC_EDIT6                       2028
#define IDC_EDIT7                       2029
#define IDC_EDIT8                       2030
#define IDC_EDIT9                       2031
#define IDC_EDIT10                      2032
#define IDC_EDIT11                      2033
#define IDC_EDIT12                      2034
#define IDC_BUTTON3                     2035
#define IDC_BUTTON4                     2036
#define IDC_BUTTON5                     2037
#define IDC_BUTTON6                     2038
#define IDC_BUTTON7                     2039
#define IDC_FORM_                       2039
#define IDC_COLLIDERTOOL                2039
#define IDC_BUTTON8                     2040
#define IDC_BUTTON9                     2041
#define IDC_BUTTON11                    2042
#define IDC_BUTTON10                    2043
#define IDC_BUTTON_TERRAIN_TOOL_WIRE_FRAME 2044
#define IDC_BUTTON12                    2044
#define IDC_TERRAIN_TOOL_CREATE_PROTOTYPE 2045
#define IDC_BUTTON_FORM_CREATE_UI       2046
#define IDC_UITOOL_SCREEN               2047
#define IDC_LIST_UI                     2048
#define IDC_BUTTON_UITOOL_SAVE_UI       2049
#define IDC_BUTTON_UITOOL_DELETE_IN_SCENE 2049
#define IDC_BUTTON_UITOOL_LOAD_UI       2050
#define IDC_EDIT_UITOOL_POS_X           2051
#define IDC_EDIT_UITOOL_POS_Y           2052
#define IDC_EDIT_UITOOL_SCALE_X         2053
#define IDC_EDIT_UITOOL_SCALE_Y         2054
#define IDC_BUTTON_UITOOL_SAVE_UI2      2055
#define IDC_BUTTON_UITOOL_ADD_TO_SCENE  2056
#define IDC_LIST_UITOOL_PLACED_UI       2057
#define IDC_PICTURE_UI_TOOL_PREVIEW     2058
#define IDC_FORM_PICTURE_PROTOTYPE_ORTH 2059
#define IDC_FORM_BUTTON_CREATE_UI_PROTOTYPE 2060
#define IDC_FORM_EDIT_CAM_POS_X         2061
#define IDC_FORM_EDIT_CAM_POS_Y         2062
#define IDC_FORM_EDIT_CAM_POS_Z         2063
#define IDC_FORM_EDIT_BACK_CURLING_ON_OFF 2064
#define IDC_FORM_BUTTON_BACK_CURLING    2065
#define IDC_LOTOBJECTTOOL_EDIT_POS_X    2066
#define IDC_LOTOBJECTTOOL_EDIT_POS_Y    2067
#define IDC_LOTOBJECTTOOL_EDIT_POS_Z    2068
#define IDC_LOTOBJECTTOOL_EDIT_NUM_X    2069
#define IDC_LOTOBJECTTOOL_EDIT_NUM_Y    2070
#define IDC_LOTOBJECTTOOL_EDIT_NUM_Z    2071
#define IDC_LOTOBJECTTOOL_BUTTON_SET    2072
#define IDC_FORM_BUTTON_CREATE_LOT_OBJECT 2073
#define IDC_LOTOBJECTTOOL_EDIT_SCALE_Y  2074
#define IDC_LOTOBJECTTOOL_EDIT_SCALE_Z  2075
#define IDC_LOTOBJECTTOOL_EDIT_SCALE_X  2076
#define IDC_PROTOTYPE_ROT_X             3001
#define IDC_PROTOTYPE_ROT_Y             3002
#define IDC_PROTOTYPE_ROT_Z             3003
#define IDC_PROTOTYPE_ROT_SLIDER_X      3004
#define IDC_PROTOTYPE_ROT_SLIDER_Y      3005
#define IDC_PROTOTYPE_ROT_SLIDER_Z      3006
#define IDC_PROTOTYPE_ROT_RESET         3007
#define IDC_PROTOTYPE_SIZE_X            3008
#define IDC_PROTOTYPE_SIZE_Y            3009
#define IDC_PROTOTYPE_SIZE_Z            3010
#define IDC_PROTOTYPE_SIZE_SET          3011
#define IDC_RADIO_PROTOTYPE_RECT        3012
#define IDC_RADIO_PROTOTYPE_CUBE        3013
#define IDC_PROTOTYPE_PICTURE           3014
#define IDC_PROTOTYPE_IMAGE_LIST        3015
#define IDC__PROTOTYPE_SAVE             3016
#define IDC_PROTOTYPE_POS_X             3017
#define IDC_PROTOTYPE_POS_Y             3018
#define IDC_PROTOTYPE_POS_Z             3019
#define IDC_PROTOTYPE_POS_SET           3020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        320
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1065
#define _APS_NEXT_SYMED_VALUE           317
#endif
#endif
